### ISSUE TITLE
It is not work in blazor>0.5.0

### ISSUE THREAD

**Issue by w8w8w8** [Appizeo/Blazor.Polyfill#2]
when I update blazor 0.5.0. then this js not work. how to fix it ? please

**Comment by Daddoon** [comment]
I don't have updated yet to 0.5.0 my own projects.
Can you please provide errors in your console, to ensure it's related to Blazor.Polyfill ?

Thanks !

**Comment by w8w8w8** [comment]
![1](https://user-images.githubusercontent.com/4744039/43388011-97c87b36-941a-11e8-843c-22884e96d2bd.png)
![2](https://user-images.githubusercontent.com/4744039/43388015-9c50b1e6-941a-11e8-9362-c639ff93dd95.png)

I think because the js file is renamed "blazor.webassembly.js",but i do not know how to fix it!
thank you !

**Comment by Daddoon** [comment]
Actually, this error may throw of the required Polyfills are not present at Blazor.js loading.
Blazor.Polyfill must be loaded **before** Blazor.js in the script loading pipeline.

Can you show me your **index.html** ? The polyfill script must be inserted before any Blazor script in your file.

Are you using blazor.polyfill.js or blazor.polyfill.min.js ?

Thanks !

**Comment by w8w8w8** [comment]
my index.html code :
`<body>
    <app>Loading...</app>
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="js/blazor.polyfill.js"></script>
    <script src="js/jquery-v1.12.4.min.js"></script>
    <script src="js/bootstrap3.min.js"></script>
    <script src="js/JsInterop.js"></script>
    <script src="js/run.js"></script>

</body>`
this url  is the blazor blog example:
https://blogs.msdn.microsoft.com/webdev/2018/07/25/blazor-0-5-0-experimental-release-now-available/

and my chrome console like this 
![3](https://user-images.githubusercontent.com/4744039/43388668-5547364c-941c-11e8-8391-a36081e43ef4.png)

**Comment by Daddoon** [comment]
Ok !

As stated before, it should look like this instead:

```
<script src="js/blazor.polyfill.js"></script>
<script src="_framework/blazor.webassembly.js"></script>
<script src="js/jquery-v1.12.4.min.js"></script>
<script src="js/bootstrap3.min.js"></script>
<script src="js/JsInterop.js"></script>
<script src="js/run.js"></script>
```

The required dependency will be then available for the _framework/blazor.webassembly.js file.

**Comment by w8w8w8** [comment]
good,it work ,and thank you! thank  you!

**Comment by Daddoon** [comment]
Cool ! Thanks !
Closing !
